version: '3.8'

services: 
  mydatabase: 
    image: mysql:5
    environment:  
      MYSQL_ROOT_PASSWORD: Um@101112

  mywordpress: 
    image: wordpress    
    ports: 
      - "8888:80"
    depends_on:          
      - mydatabase

